Prefix the drag event types with SQ
This is required for compatibility with MSVC (2015), otherwise there's a namespace conflict:
>c:\program files (x86)\windows kits\8.1\include\um\oleidl.h(3541): error C2059: erreur de syntaxe : 'constant'

The offending code is:

        HRESULT ( STDMETHODCALLTYPE *DragEnter )(