Salvage the stack builds
For some reasons (?) the VM_LABEL macro is now barking like this:

>../../spurstack64src/vm/gcc3x-interp.c:9419:5: error: invalid symbol redefinition
>                                VM_LABEL(extPushPseudoVariable);
>                                ^
>In file included from ../../spurstack64src/vm/gcc3x-interp.c:29:
>In file included from ../../platforms/iOS/vm/Common/sqGnu.h:46:
>In file included from ../../platforms/Cross/vm/sq.h:252:
>../../platforms/iOS/vm/OSX/sqPlatformSpecific.h:174:52: note: expanded from macro 'VM_LABEL'
>#         define VM_LABEL(foo) asm("\n.globl _L" #foo "\n_L" #foo ":")
>                                                         ^
><inline asm>:3:1: note: instantiated into assembly here
>_LextPushPseudoVariable:
>^

Since this does not happen in cog builds, avoid brainstorming and just use the same workaround.